"""empty message

Revision ID: 124a8d5f7051
Revises: 
Create Date: 2021-11-12 13:38:18.031320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124a8d5f7051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lottery_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lottery')
    # ### end Alembic commands ###
