"""empty message

Revision ID: 30d938dd65dd
Revises: 
Create Date: 2021-12-07 11:43:43.614065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d938dd65dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lottery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lottery_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lottery')
    # ### end Alembic commands ###
