"""empty message

Revision ID: 5019e6c0ca58
Revises: 
Create Date: 2021-12-08 11:47:22.862202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5019e6c0ca58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lottery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lottery_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lottery')
    # ### end Alembic commands ###
